# Generated by Django 5.0.6 on 2024-05-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
                ('caminho', models.CharField(max_length=200)),
                ('codigo_status', models.IntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
