# Generated by Django 5.0.6 on 2024-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='codigo_status',
            new_name='code_status',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='data_hora',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='caminho',
            new_name='endpoint',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='metodo',
            new_name='method',
        ),
    ]
